config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # get "welcome/index", to: "welcome#index"

  # Defines the root path route ("/")
  resources :students
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assembly.rb
class Assembly < ApplicationRecord
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :student
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/channel_subscribtion.rb
class ChannelSubscribtion < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :students
  validates :name, :description, presence: true
end

app/models/demo.rb
class Demo < ApplicationRecord
  has_one :sub_demo
end

app/models/part.rb
class Part < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :student_projects
  has_many :students, through: :student_projects
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :blogs
  has_and_belongs_to_many :courses

  has_many :student_projects
  has_many :projects, through: :student_projects

  validates :first_name, :last_name, :email, presence: true
end

app/models/student_project.rb
class StudentProject < ApplicationRecord
  belongs_to :student
  belongs_to :project
end

app/models/sub_demo.rb
class SubDemo < ApplicationRecord
  belongs_to :demo
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/video_channel.rb
class VideoChannel < ApplicationRecord
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_path, status: :see_other, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :description)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_path, notice: 'Student was successfully created.' }
        format.json { render :index, status: :created, location: @students }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_path(@student), notice: 'Student was successfully updated.' }
        format.json { render :index, status: :updated, location: @students }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @student.destroy
        format.html { redirect_to student_path(@student), notice: 'Student was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :date_of_birth, :address, :contact)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>
    <% if @student.errors.any? %>
        <h2><%= pluralize(@student.errors.count, "error") %> prohibited this post from being saved:</h2>
        <% @student.errors.full_messages.each do |error| %>
            <p><%= error %></p>
        <% end %>
    <% end %>
    <div>
      <%= form.label :first_name %><br>
      <%= form.text_field :first_name %>
    </div>
    <div>
      <%= form.label :last_name %><br>
      <%= form.text_field :last_name %>
    </div>
    <div>
      <%= form.label :email %><br>
      <%= form.email_field :email %>
    </div>
    <div>
      <%= form.label :date_of_birth %><br>
      <%= form.date_field :date_of_birth %>
    </div>
    <div>
      <%= form.label :address %><br>
      <%= form.text_field :address %>
    </div>
    <div>
      <%= form.label :contact %><br>
      <%= form.text_field :contact %>
    </div>

    <br>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render "form", student: @student %>

app/views/students/index.html.erb
<h1>List Student</h1>

<p><%= notice %></p>

<%= link_to 'New Student', new_student_path %>
<table border="1">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @students.each do |student| %>
            <tr>
                <td><%= student.first_name %></td>
                <td><%= student.last_name %></td>
                <td><%= student.email %></td>
                <td>
                    <%= link_to 'Detail', student %> |
                    <%= link_to 'Edit', edit_student_path(student) %> |
                    <%= link_to 'Delete', student, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<!-- <%= render partial: "form", locals: { student: @student } %> -->
<%= render "form", student: @student %>

app/views/students/show.html.erb
<h1>Show student</h1>

<span>First Name : <%= @student.first_name %></span><br>
<span>Last Name : <%= @student.last_name %></span><br>
<span>Email : <%= @student.email %></span><br><br>

<%= link_to 'Back', students_path %> | <%= link_to 'Edit', edit_student_path(@student) %>